#define EXS_NEED_FLOAT 0
/* exsecutor: reach backend */
/* Generated by exsc --emitte c. Do not edit: the text of this prologue is a
 * function of exsc's own bytes (docs/design/c-backend.md D5), the way the
 * reference backend's prelude blob is. */
#include <stdint.h>
#include <limits.h>
#ifndef EXS_NEED_FLOAT
#define EXS_NEED_FLOAT 1
#endif
#if EXS_NEED_FLOAT
#include <float.h>
#endif

#if !defined(__GNUC__) && !defined(__clang__)
# error "exsecutor: the emitted C is C11 plus a GCC/Clang extension set (ADR 0012)"
#endif
#if !defined(__BYTE_ORDER__) || !defined(__ORDER_LITTLE_ENDIAN__) || !defined(__ORDER_BIG_ENDIAN__)
# error "exsecutor: __BYTE_ORDER__ is required to select the nativus helpers"
#endif
#if defined(__FAST_MATH__)
# error "exsecutor: -ffast-math is refused (spec 5.4)"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
# error "exsecutor: -ffinite-math-only is refused (spec 5.4)"
#endif

#if EXS_NEED_FLOAT
/* ---- IEEE binary32/64: the numeric subset's one target (spec 5.4) -------
 * ADR 0012's rung (b), spelled with <float.h> exactly as ADR 0012 names it
 * -- freestanding-safe, unlike __STDC_IEC_559__ (which a freestanding
 * implementation may define without honouring). `float` is binary32 and
 * `double` binary64, and no operation gains precision: FLT_EVAL_METHOD 0
 * is what makes `float op float` a FLOAT operation in C rather than a
 * double one (C's usual arithmetic conversions leave the type alone, but
 * only an evaluation method of 0 leaves the RESULT alone). Subnormals are
 * values (subnormales conservata); where C11's <float.h> stays silent
 * about them (the *_HAS_SUBNORM macros are optional before C23) the
 * runtime's MXCSR/FPCR image is what enforces it -- FTZ and DAZ clear,
 * which the reference prelude's 0x1F80 image also carries. */
_Static_assert(FLT_RADIX == 2, "exsecutor: the numeric subset is IEEE binary32/64 (spec 5.4)");
_Static_assert(FLT_MANT_DIG == 24 && DBL_MANT_DIG == 53,
               "exsecutor: float is binary32 and double is binary64");
_Static_assert(FLT_MAX_EXP == 128 && DBL_MAX_EXP == 1024,
               "exsecutor: binary32/64 exponent widths");
#if FLT_EVAL_METHOD != 0
# error "exsecutor: FLT_EVAL_METHOD must be 0 (spec 5.4: one rounding, in the operands' own width)"
#endif
#if defined(FLT_HAS_SUBNORM) && FLT_HAS_SUBNORM != 1
# error "exsecutor: float subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif
#if defined(DBL_HAS_SUBNORM) && DBL_HAS_SUBNORM != 1
# error "exsecutor: double subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif

/* Contraction (spec 5.4 contractio explicita; ADR 0012 problem 1). One IR
 * op is one C statement, so no emitted statement ever holds a
 * multiply-and-add tree to contract -- `fma` is the only contraction the
 * language has, it is refused by name in both backends, and this pragma is
 * the belt to that brace. `#pragma STDC FP_CONTRACT OFF` is NOT emitted:
 * measured to do nothing in both compilers, and GCC warns about it under
 * -Wall (c-backend.md D3, finding 12). Clang has nothing that works from
 * inside the source (`#pragma clang fp contract(off)` does not override a
 * command-line -ffp-contract=fast), so nothing is said to it and nothing
 * is lied about. */
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC optimize("fp-contract=off")
#endif
#endif /* EXS_NEED_FLOAT */

_Static_assert(CHAR_BIT == 8, "exsecutor: CHAR_BIT must be 8");
_Static_assert((-1 & 3) == 3, "exsecutor: two's complement");
_Static_assert(sizeof(unsigned) * CHAR_BIT >= 32, "exsecutor: unsigned holds a byte and a shift");

/* The trap hook: the ONE symbol a library-mode unit imports. Whoever links
 * it supplies the body (c-backend.md D1). Kinds are prelude/README.md's:
 * 1 numeric (overflow, a shift count past the width, a failed chk),
 * 5 terminus. */
_Noreturn void exsrt_abortus(unsigned kind);

/* Every integer value of any uN or iN is held in a uint64_t in canonical
 * form (ssa-ir.md 2.2): a uN zero-extended, an iN sign-extended. Every
 * helper assumes canonical inputs and returns a canonical result. All
 * arithmetic is on uint64_t, whose overflow C defines as modular, so no
 * emitted operation is undefined and -fwrapv / -ftrapv are irrelevant. */
static inline uint64_t exsi_mask(unsigned n)
{ return n == 64 ? UINT64_MAX : (UINT64_C(1) << n) - 1; }
static inline uint64_t exsi_norm_u(uint64_t x, unsigned n)
{ return x & exsi_mask(n); }
static inline uint64_t exsi_norm_i(uint64_t x, unsigned n)
{ uint64_t s = UINT64_C(1) << (n - 1); return ((x & exsi_mask(n)) ^ s) - s; }

#if EXS_NEED_FLOAT
/* Floats from their bits -- `fconst`'s round-trip. `fconst F bits` carries
 * the RAW bit pattern (ssa-ir.md 2.3: bits, never decimal text) and it must
 * come back exactly: payload bits included (a NaN's payload survives fneg),
 * sign included (-0.0 is a different constant from 0.0), subnormal bits
 * included (subnormales conservata). A C floating literal cannot spell any
 * of that -- a hex floating literal for an out-of-range pattern loses the
 * NaN payload and the quiet bit -- so the pattern is written as an integer
 * constant and re-read through the object representation:
 * __builtin_memcpy, the GCC-recommended bit-cast, already measured and on
 * D3's extension list for `copy n` (c-backend.md finding 13). Assumes a
 * float's byte order is the integer byte order -- true of every target in
 * scope: x86_64, riscv64 and mips64 are each uniform in their byte order,
 * which is what the emitted `exsi_ld_n` selection also assumes. */
static inline float exsi_f32_from_bits(uint32_t b)
{ float f; __builtin_memcpy(&f, &b, sizeof f); return f; }
static inline double exsi_f64_from_bits(uint64_t b)
{ double d; __builtin_memcpy(&d, &b, sizeof d); return d; }

/* The way back, for `store F`: the float's bit pattern as the integer the
 * byte-store helpers carry. Same bit-cast, same assumption a few lines
 * above (a float's byte order is the integer byte order) -- the round trip
 * store-then-load is the identity on every --hospes row, which is all
 * memory consistency asks of a bit pattern with no numeric reading. */
static inline uint32_t exsi_bits_from_f32(float f)
{ uint32_t b; __builtin_memcpy(&b, &f, sizeof b); return b; }
static inline uint64_t exsi_bits_from_f64(double d)
{ uint64_t b; __builtin_memcpy(&b, &d, sizeof b); return b; }

/* The vector float group (spec 5.4's vf32.N/vf64.N; ssa-ir.md 2.2: N lanes
 * of binary32/binary64, N in {2,4,8}), as C's vector_size extension -- one
 * of the GCC/Clang extensions ADR 0012's set already carries. One IR
 * vadd/vsub/vmul/vdiv is one C statement on the whole vector (the one
 * op-per-statement rule), and the operator's elementwise lowering is the
 * ONE IEEE rounding per lane the reference's packed addps/addpd carries:
 * GCC and Clang both lower vector_size arithmetic elementwise on x86-64
 * and soft-lower it on the mips64-none cross target, which is what keeps
 * cross=yes alive for this wave. NO intrinsics and no <emmintrin.h>-family
 * header: those spellings do not exist on the cross target. */
typedef float exs_vf32_2 __attribute__((vector_size(8)));
typedef float exs_vf32_4 __attribute__((vector_size(16)));
typedef float exs_vf32_8 __attribute__((vector_size(32)));
typedef double exs_vf64_2 __attribute__((vector_size(16)));
typedef double exs_vf64_4 __attribute__((vector_size(32)));
typedef double exs_vf64_8 __attribute__((vector_size(64)));
/* The N = 8 helpers carry 32/64-byte vectors, and both compilers note at
 * their definitions (GCC) or call sites (Clang) that passing such a vector
 * without AVX enabled "changes the ABI" (-Wpsabi). That warning is a
 * statement about TWO translation units compiled with different -m flags
 * sharing a function boundary -- and no boundary here carries a vector:
 * the helpers are `static inline` inside the single emitted unit, and the
 * unit's one imported/exported symbol (exs_initium's unsigned char *) is a
 * scalar. The note is noise for this blob and is switched off for it, the
 * way -Wno-unused-function is for the rest of it (recorded, not hidden). */
#if defined(__clang__)
# pragma clang diagnostic ignored "-Wpsabi"
#elif defined(__GNUC__)
# pragma GCC diagnostic ignored "-Wpsabi"
#endif
_Static_assert(sizeof(exs_vf32_2) == 8 && sizeof(exs_vf32_4) == 16 &&
               sizeof(exs_vf32_8) == 32,
               "exsecutor: a vf32.N is N binary32 lanes, packed (spec 5.4)");
_Static_assert(sizeof(exs_vf64_2) == 16 && sizeof(exs_vf64_4) == 32 &&
               sizeof(exs_vf64_8) == 64,
               "exsecutor: a vf64.N is N binary64 lanes, packed (spec 5.4)");

/* A vector in memory is its lanes' raw IEEE images, back to back in
 * subscript order, each element in the target's byte order -- the same
 * assumption the scalar helpers above name, so the nativus round trip is
 * the identity on every --hospes row. The load/store helpers are memcpy
 * bit baggage exactly the way the scalar float path's from_bits/bits_from
 * helpers are: no lane is read numerically on the path, so a NaN payload,
 * -0.0's sign and a subnormal's bits survive every copy (subnormales
 * conservata). */
static inline exs_vf32_2 exsi_ld_vf32_2(const unsigned char *p)
{ exs_vf32_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_4 exsi_ld_vf32_4(const unsigned char *p)
{ exs_vf32_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_8 exsi_ld_vf32_8(const unsigned char *p)
{ exs_vf32_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_2 exsi_ld_vf64_2(const unsigned char *p)
{ exs_vf64_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_4 exsi_ld_vf64_4(const unsigned char *p)
{ exs_vf64_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_8 exsi_ld_vf64_8(const unsigned char *p)
{ exs_vf64_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline void exsi_st_vf32_2(unsigned char *p, exs_vf32_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_4(unsigned char *p, exs_vf32_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_8(unsigned char *p, exs_vf32_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_2(unsigned char *p, exs_vf64_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_4(unsigned char *p, exs_vf64_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_8(unsigned char *p, exs_vf64_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }

/* itof from a signed integer's canonical bits. The carrier holds an iN
 * sign-extended (ssa-ir.md 2.2), so the two's-complement value IS the bit
 * pattern -- but C leaves a uint64_t -> int64_t conversion that does not
 * fit IMPLEMENTATION-DEFINED, a fact this prologue asserts nowhere and
 * refuses to rely on, so the bits are re-read as int64_t exactly the way
 * fconst re-reads a pattern as a float. The signed type appears here and
 * nowhere else: this is a conversion into a float, not arithmetic, and the
 * one-op-per-statement rule keeps it out of any expression a compiler
 * could contract. */
static inline int64_t exsi_i64_from_bits(uint64_t b)
{ int64_t s; __builtin_memcpy(&s, &b, sizeof s); return s; }

#endif /* EXS_NEED_FLOAT */

static inline uint64_t exsi_add_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? t < a : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_add_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? ((((a ^ t) & (b ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? a < b : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? ((((a ^ b) & (a ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
/* mul checks by DIVISION at every width rather than in a wider type: GCC
 * provides __int128 only where __SIZEOF_INT128__ is defined, which excludes
 * 32-bit-pointer targets such as o64 (c-backend.md finding 5). b > M / a is
 * exact. */
static inline uint64_t exsi_mul_u(uint64_t a, uint64_t b, unsigned n)
{ if (n <= 32) { uint64_t t = a * b; if (t > exsi_mask(n)) exsrt_abortus(1); return t; }
  if (a != 0 && b > exsi_mask(n) / a) exsrt_abortus(1);
  return a * b; }
static inline uint64_t exsi_mul_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t sa = a >> 63, sb = b >> 63;
  uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
  uint64_t neg = sa ^ sb;
  uint64_t lim = neg ? UINT64_C(1) << (n - 1) : (UINT64_C(1) << (n - 1)) - 1;
  if (ma != 0 && mb > lim / ma) exsrt_abortus(1);
  { uint64_t p = ma * mb; return neg ? 0 - p : p; } }   /* canonical by construction */

/* div and rem -- spec 5.4 as decided 2026-09-25: the quotient TRUNCATED
 * TOWARD ZERO and the remainder's sign FOLLOWING THE DIVIDEND, so that
 * `a == (a/b)*b + (a rem b)` holds at every pair of signs. Both trap on a
 * zero divisor, and both trap on T_MIN / -1 -- `rem` included, whose
 * mathematical value there is 0: it is the remainder OF a division that
 * does not exist, and a `rem` answering 0 where its own `div` traps would
 * falsify the identity at the one pair of operands two instructions can
 * check it on. emit.inc's __bfa_emit_divrem argues the same two paragraphs
 * for the reference; these helpers are the same function, not a second
 * opinion about it.
 *
 * THE CHECKS PRECEDE THE DIVISION, where every other trapping helper above
 * checks after, and they have to for two independent reasons. The semantic
 * one: `rem`'s result carries no trace of the overflow (T_MIN rem -1 is 0,
 * a perfectly good value of T), so there is nothing to check afterwards.
 * The harness one: every fixture is compiled `-fsanitize=undefined
 * -fno-sanitize-recover=all`, so a helper that DIVIDED first would abort
 * inside UBSan -- wrong status, wrong text, exsrt_abortus never reached --
 * on precisely the two inputs whose trap is the thing being tested.
 *
 * T_MIN IS T'S OWN, NOT INT64_MIN. In `i8`, -128 / -1 is 128, which no
 * `i8` holds, and the 64-bit division of a sign-extended -128 by -1
 * computes it without a murmur; tests/ir/trap_div_minneg1.ir is that case
 * and nothing else. So the comparison is against -2^(N-1) for the operand
 * type's own N. At N = 64 the same line also stands in for the hardware's
 * divide error, which the reference likewise turns into kind 1 rather than
 * a second signal that depends on the width.
 *
 * NO SIGNED C DIVISION ANYWHERE. The signed pair divides MAGNITUDES and
 * puts the sign back, exactly as exsi_mul_i does, so the carrier's
 * implementation-defined uint64_t -> int64_t conversion is never needed
 * (this file relies on it nowhere but exsi_i64_from_bits, and then through
 * memcpy) and UBSan's signed-overflow check is never armed. `0 - x` on a
 * uint64_t is modular C, not overflow. The magnitude of T_MIN is 2^63,
 * which `0 - a` leaves as 2^63 -- still the right unsigned magnitude.
 *
 * NO NORMALISATION, and the proof rather than the habit. With a zero
 * divisor and T_MIN / -1 excluded the result is ALREADY a value of T:
 * |a/b| <= |a| for |b| >= 1, so the only out-of-range quotient is -T_MIN,
 * which is precisely the case just excluded; and |a rem b| < |b| <=
 * 2^(N-1), in range at every sign. `0 - q` on an in-range magnitude leaves
 * the value sign-extended, which is the canonical form (ssa-ir.md 2.2).
 *
 * n IS UNUSED IN THE UNSIGNED PAIR and the parameter still stays. A uN
 * quotient is at most the dividend and a uN remainder is less than the
 * divisor, so neither can leave the type, and unsigned division has no
 * T_MIN case to exclude -- but the emitter writes ONE call shape for every
 * row of the helper table, so the argument is passed and discarded the way
 * exsi_subs_u discards it. */
static inline uint64_t exsi_div_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a / b; }
static inline uint64_t exsi_rem_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a % b; }
static inline uint64_t exsi_div_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
    uint64_t q = ma / mb;
    return (sa ^ sb) ? 0 - q : q; } }                    /* canonical by construction */
static inline uint64_t exsi_rem_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;
    uint64_t r = ma % mb;
    return sa ? 0 - r : r; } }                           /* the DIVIDEND's sign */

static inline uint64_t exsi_adds_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b; return (n == 64 ? t < a : t > exsi_mask(n)) ? exsi_mask(n) : t; }
static inline uint64_t exsi_subs_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; return a < b ? 0 : a - b; }
static inline uint64_t exsi_adds_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ t) & (b ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }
static inline uint64_t exsi_subs_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ b) & (a ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }

/* A count >= the width traps, as spec 5.4 says it must ("traps, as + traps
 * on overflow"); after the check c < n <= 64, so every C shift below is
 * defined. A negative iN count is a huge unsigned and traps, which is what
 * the reference's `jae` does too. */
static inline uint64_t exsi_shl_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_u(a << c, n); }
static inline uint64_t exsi_shl_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_i(a << c, n); }
static inline uint64_t exsi_shr_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return a >> c; }
/* arithmetic right shift without a signed shift: the sign replicated by a
 * mask. c == 0 is split out because (x << 64) would be a shift by the
 * type's width. */
static inline uint64_t exsi_shr_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1);
  return c == 0 ? a : (a >> c) | ((0 - (a >> 63)) << (64 - c)); }

/* Byte-at-a-time, with explicit shifts: the emitted text depends on no
 * assumption about the C host's byte order and asserts none (c-backend.md
 * D2). p[i] is an unsigned char promoted to int and converted straight to
 * uint64_t by the | -- a value in 0..255, never operated on as an int. */
static inline uint64_t exsi_ld_be(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v = (v << 8) | p[i]; return v; }
static inline uint64_t exsi_ld_le(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v |= (uint64_t)p[i] << (8 * i); return v; }
static inline void exsi_st_be(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * (k - 1 - i))); }
static inline void exsi_st_le(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * i)); }
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# define exsi_ld_n exsi_ld_le
# define exsi_st_n exsi_st_le
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define exsi_ld_n exsi_ld_be
# define exsi_st_n exsi_st_be
#else
# error "exsecutor: unknown __BYTE_ORDER__"
#endif

_Static_assert(sizeof(void *) == 8, "exsecutor: this hospes has 64-bit addresses");

uint64_t exs_admitte_ipv4(unsigned char *p0, uint64_t p1);
uint64_t exs_octetus(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_ordo_ipv4(unsigned char *p0, uint64_t p1);
uint64_t exs_numerus_iudica(unsigned char *p0, uint64_t p1, uint64_t p2);
uint64_t exs_admitte_portum(unsigned char *p0, uint64_t p1);
uint64_t exs_admitte_intervallum(unsigned char *p0, uint64_t p1);

uint64_t exs_admitte_ipv4(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v20;
    uint64_t v22;
    unsigned char *v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v33;
    uint64_t v35;
    uint64_t v36;
    uint64_t v37;
    uint64_t v39;
    uint64_t v41;
    uint64_t v42;
    uint64_t v43;
    uint64_t v44;
    uint64_t v45;
    uint64_t v47;
    uint64_t v48;
    uint64_t v50;
    uint64_t v52;
    uint64_t v53;
    uint64_t v55;
    uint64_t v57;
    uint64_t v58;
    uint64_t v60;
    uint64_t v62;
    uint64_t v63;
    uint64_t v65;
    uint64_t v66;
    uint64_t v67;
    uint64_t v69;
    uint64_t v72;
    uint64_t v73;
    uint64_t v74;
    uint64_t v76;
    uint64_t v79;
    uint64_t v80;
    uint64_t v81;
    uint64_t v82;
    uint64_t v83;
    uint64_t v84;
    uint64_t v85;
    uint64_t v86;
    uint64_t v87;
    uint64_t v89;
    uint64_t v91;
    uint64_t v92;
    uint64_t v95;
    uint64_t v96;
    uint64_t v98;
    uint64_t v99;
    uint64_t v100;
    uint64_t v101;
    uint64_t v102;
    uint64_t v103;
    uint64_t v104;
    uint64_t v105;
    uint64_t v107;
    uint64_t v109;
    uint64_t v110;
    uint64_t v112;
    uint64_t v114;
    uint64_t t19;
    uint64_t t29;
    uint64_t t35;
    uint64_t t72;
    uint64_t t79;
    uint64_t t98;
    uint64_t t99;
    uint64_t t100;
    uint64_t t101;
    uint64_t t102;
    uint64_t t103;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(0);
    v4 = (v2 == v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(1);
    return v6;
b3:
    v8 = UINT64_C(15);
    v9 = (v2 > v8);
    if (v9) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v11 = UINT64_C(2);
    return v11;
b5:
    v13 = UINT64_C(0);
    v14 = UINT64_C(0);
    v15 = UINT64_C(0);
    v16 = UINT64_C(0);
    v17 = UINT64_C(0);
    t79 = v15;
    t72 = v16;
    t35 = v13;
    t29 = v14;
    t19 = v17;
    v79 = t79;
    v72 = t72;
    v35 = t35;
    v29 = t29;
    v19 = t19;
    goto b6;
b6:
    v20 = (v19 < v2);
    if (v20) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v22 = UINT64_C(16);
    if (v19 >= v22) exsrt_abortus(1);
    v24 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v19 * 1);
    v25 = exsi_norm_u(exsi_ld_n(v24 + 0, 1), 8);
    v26 = UINT64_C(46);
    v27 = (v25 == v26);
    if (v27) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    v104 = UINT64_C(3);
    v105 = (v35 != v104);
    if (v105) {
        goto b32;
    } else {
        goto b33;
    }
b9:
    v95 = UINT64_C(1);
    v96 = v19 + v95;
    t79 = v103;
    t72 = v100;
    t35 = v99;
    t29 = v98;
    t19 = v96;
    v79 = t79;
    v72 = t72;
    v35 = t35;
    v29 = t29;
    v19 = t19;
    goto b6;
b10:
    v30 = UINT64_C(0);
    v31 = (v29 == v30);
    if (v31) {
        goto b12;
    } else {
        goto b13;
    }
b11:
    v47 = UINT64_C(48);
    v48 = (v25 < v47);
    if (v48) {
        goto b17;
    } else {
        goto b18;
    }
b12:
    v33 = UINT64_C(4);
    return v33;
b13:
    v36 = UINT64_C(3);
    v37 = (v35 >= v36);
    if (v37) {
        goto b14;
    } else {
        goto b15;
    }
b14:
    v39 = UINT64_C(4);
    return v39;
b15:
    v41 = UINT64_C(1);
    v42 = exsi_add_u(v35, v41, 8);
    v43 = UINT64_C(0);
    v44 = UINT64_C(0);
    v45 = UINT64_C(0);
    t103 = v44;
    t100 = v45;
    t99 = v42;
    t98 = v43;
    v103 = t103;
    v100 = t100;
    v99 = t99;
    v98 = t98;
    goto b16;
b16:
    goto b9;
b17:
    v50 = UINT64_C(3);
    return v50;
b18:
    v52 = UINT64_C(57);
    v53 = (v25 > v52);
    if (v53) {
        goto b19;
    } else {
        goto b20;
    }
b19:
    v55 = UINT64_C(3);
    return v55;
b20:
    v57 = UINT64_C(3);
    v58 = (v29 >= v57);
    if (v58) {
        goto b21;
    } else {
        goto b22;
    }
b21:
    v60 = UINT64_C(5);
    return v60;
b22:
    v62 = UINT64_C(0);
    v63 = (v29 == v62);
    if (v63) {
        goto b23;
    } else {
        goto b24;
    }
b23:
    v65 = UINT64_C(0);
    v66 = UINT64_C(48);
    v67 = (v25 == v66);
    if (v67) {
        goto b25;
    } else {
        t102 = v65;
        v102 = t102;
        goto b26;
    }
b24:
    v73 = UINT64_C(1);
    v74 = (v72 == v73);
    if (v74) {
        goto b28;
    } else {
        goto b29;
    }
b25:
    v69 = UINT64_C(1);
    t102 = v69;
    v102 = t102;
    goto b26;
b26:
    t101 = v102;
    v101 = t101;
    goto b27;
b27:
    v80 = UINT64_C(10);
    v81 = exsi_mul_u(v79, v80, 32);
    v82 = exsi_norm_u(exsi_norm_u(v25, 8), 32);
    v83 = UINT64_C(48);
    v84 = exsi_sub_u(v82, v83, 32);
    v85 = exsi_add_u(v81, v84, 32);
    v86 = UINT64_C(255);
    v87 = (v85 > v86);
    if (v87) {
        goto b30;
    } else {
        goto b31;
    }
b28:
    v76 = UINT64_C(6);
    return v76;
b29:
    t101 = v72;
    v101 = t101;
    goto b27;
b30:
    v89 = UINT64_C(7);
    return v89;
b31:
    v91 = UINT64_C(1);
    v92 = exsi_add_u(v29, v91, 8);
    t103 = v85;
    t100 = v101;
    t99 = v35;
    t98 = v92;
    v103 = t103;
    v100 = t100;
    v99 = t99;
    v98 = t98;
    goto b16;
b32:
    v107 = UINT64_C(4);
    return v107;
b33:
    v109 = UINT64_C(0);
    v110 = (v29 == v109);
    if (v110) {
        goto b34;
    } else {
        goto b35;
    }
b34:
    v112 = UINT64_C(4);
    return v112;
b35:
    v114 = UINT64_C(0);
    return v114;
}

uint64_t exs_octetus(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    unsigned char *v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v22;
    uint64_t v24;
    uint64_t v25;
    uint64_t v27;
    uint64_t v28;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    uint64_t v36;
    uint64_t v41;
    uint64_t v42;
    uint64_t v44;
    uint64_t v45;
    uint64_t v46;
    uint64_t v47;
    uint64_t v50;
    uint64_t v51;
    uint64_t t8;
    uint64_t t18;
    uint64_t t30;
    uint64_t t41;
    uint64_t t44;
    uint64_t t45;
    uint64_t t46;
    uint64_t t47;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(0);
    v5 = UINT64_C(0);
    v6 = UINT64_C(0);
    t30 = v5;
    t18 = v4;
    t8 = v6;
    v30 = t30;
    v18 = t18;
    v8 = t8;
    goto b2;
b2:
    v9 = (v8 < v2);
    if (v9) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v11 = UINT64_C(16);
    if (v8 >= v11) exsrt_abortus(1);
    v13 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v8 * 1);
    v14 = exsi_norm_u(exsi_ld_n(v13 + 0, 1), 8);
    v15 = UINT64_C(46);
    v16 = (v14 == v15);
    if (v16) {
        goto b6;
    } else {
        goto b7;
    }
b4:
    return v30;
b5:
    v50 = UINT64_C(1);
    v51 = v8 + v50;
    t30 = v44;
    t18 = v41;
    t8 = v51;
    v30 = t30;
    v18 = t18;
    v8 = t8;
    goto b2;
b6:
    v19 = UINT64_C(1);
    v20 = exsi_add_u(v18, v19, 8);
    t44 = v30;
    t41 = v20;
    v44 = t44;
    v41 = t41;
    goto b8;
b7:
    v22 = (v18 == v3);
    if (v22) {
        goto b9;
    } else {
        t45 = v30;
        v45 = t45;
        goto b10;
    }
b8:
    v42 = (v41 > v3);
    if (v42) {
        goto b15;
    } else {
        goto b16;
    }
b9:
    v24 = UINT64_C(48);
    v25 = (v14 >= v24);
    if (v25) {
        goto b11;
    } else {
        t46 = v30;
        v46 = t46;
        goto b12;
    }
b10:
    t44 = v45;
    t41 = v18;
    v44 = t44;
    v41 = t41;
    goto b8;
b11:
    v27 = UINT64_C(57);
    v28 = (v14 <= v27);
    if (v28) {
        goto b13;
    } else {
        t47 = v30;
        v47 = t47;
        goto b14;
    }
b12:
    t45 = v46;
    v45 = t45;
    goto b10;
b13:
    v31 = UINT64_C(10);
    v32 = exsi_mul_u(v30, v31, 32);
    v33 = exsi_norm_u(exsi_norm_u(v14, 8), 32);
    v34 = UINT64_C(48);
    v35 = exsi_sub_u(v33, v34, 32);
    v36 = exsi_add_u(v32, v35, 32);
    t47 = v36;
    v47 = t47;
    goto b14;
b14:
    t46 = v47;
    v46 = t46;
    goto b12;
b15:
    return v44;
b16:
    goto b5;
}

uint64_t exs_ordo_ipv4(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v18;
    uint64_t v19;
    uint64_t v21;
    uint64_t v23;
    uint64_t v24;
    uint64_t v26;
    uint64_t v28;
    uint64_t v29;
    uint64_t v31;
    uint64_t v32;
    uint64_t v34;
    uint64_t v37;
    uint64_t v38;
    uint64_t v40;
    uint64_t v41;
    uint64_t v43;
    uint64_t v44;
    uint64_t v46;
    uint64_t v50;
    uint64_t v51;
    uint64_t v53;
    uint64_t v54;
    uint64_t v56;
    uint64_t v59;
    uint64_t v60;
    uint64_t v62;
    uint64_t v63;
    uint64_t v65;
    uint64_t v66;
    uint64_t v68;
    uint64_t v72;
    uint64_t v73;
    uint64_t v75;
    uint64_t v77;
    uint64_t v78;
    uint64_t v80;
    uint64_t v82;
    v1 = p0;
    v2 = p1;
    v3 = exs_admitte_ipv4(v1, v2);
    v4 = UINT64_C(0);
    v5 = (v3 != v4);
    if (v5) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v7 = UINT64_C(255);
    return v7;
b3:
    v9 = UINT64_C(0);
    v10 = exs_octetus(v1, v2, v9);
    v11 = UINT64_C(1);
    v12 = exs_octetus(v1, v2, v11);
    v13 = UINT64_C(0);
    v14 = (v10 == v13);
    if (v14) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v16 = UINT64_C(1);
    return v16;
b5:
    v18 = UINT64_C(127);
    v19 = (v10 == v18);
    if (v19) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v21 = UINT64_C(2);
    return v21;
b7:
    v23 = UINT64_C(10);
    v24 = (v10 == v23);
    if (v24) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v26 = UINT64_C(6);
    return v26;
b9:
    v28 = UINT64_C(169);
    v29 = (v10 == v28);
    if (v29) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v31 = UINT64_C(254);
    v32 = (v12 == v31);
    if (v32) {
        goto b12;
    } else {
        goto b13;
    }
b11:
    v37 = UINT64_C(172);
    v38 = (v10 == v37);
    if (v38) {
        goto b14;
    } else {
        goto b15;
    }
b12:
    v34 = UINT64_C(3);
    return v34;
b13:
    goto b11;
b14:
    v40 = UINT64_C(16);
    v41 = (v12 >= v40);
    if (v41) {
        goto b16;
    } else {
        goto b17;
    }
b15:
    v50 = UINT64_C(192);
    v51 = (v10 == v50);
    if (v51) {
        goto b20;
    } else {
        goto b21;
    }
b16:
    v43 = UINT64_C(31);
    v44 = (v12 <= v43);
    if (v44) {
        goto b18;
    } else {
        goto b19;
    }
b17:
    goto b15;
b18:
    v46 = UINT64_C(6);
    return v46;
b19:
    goto b17;
b20:
    v53 = UINT64_C(168);
    v54 = (v12 == v53);
    if (v54) {
        goto b22;
    } else {
        goto b23;
    }
b21:
    v59 = UINT64_C(100);
    v60 = (v10 == v59);
    if (v60) {
        goto b24;
    } else {
        goto b25;
    }
b22:
    v56 = UINT64_C(6);
    return v56;
b23:
    goto b21;
b24:
    v62 = UINT64_C(64);
    v63 = (v12 >= v62);
    if (v63) {
        goto b26;
    } else {
        goto b27;
    }
b25:
    v72 = UINT64_C(240);
    v73 = (v10 >= v72);
    if (v73) {
        goto b30;
    } else {
        goto b31;
    }
b26:
    v65 = UINT64_C(127);
    v66 = (v12 <= v65);
    if (v66) {
        goto b28;
    } else {
        goto b29;
    }
b27:
    goto b25;
b28:
    v68 = UINT64_C(7);
    return v68;
b29:
    goto b27;
b30:
    v75 = UINT64_C(5);
    return v75;
b31:
    v77 = UINT64_C(224);
    v78 = (v10 >= v77);
    if (v78) {
        goto b32;
    } else {
        goto b33;
    }
b32:
    v80 = UINT64_C(4);
    return v80;
b33:
    v82 = UINT64_C(0);
    return v82;
}

uint64_t exs_numerus_iudica(unsigned char *p0, uint64_t p1, uint64_t p2)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v9;
    uint64_t v10;
    uint64_t v12;
    uint64_t v14;
    uint64_t v15;
    uint64_t v17;
    uint64_t v18;
    uint64_t v20;
    unsigned char *v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v27;
    uint64_t v29;
    uint64_t v30;
    uint64_t v32;
    uint64_t v34;
    uint64_t v35;
    uint64_t v36;
    uint64_t v37;
    uint64_t v38;
    uint64_t v39;
    uint64_t v40;
    uint64_t v42;
    uint64_t v43;
    uint64_t v45;
    uint64_t v46;
    unsigned char *v48;
    uint64_t v49;
    uint64_t v50;
    uint64_t v51;
    uint64_t v53;
    uint64_t v54;
    uint64_t v56;
    uint64_t v59;
    uint64_t v60;
    uint64_t v62;
    uint64_t v64;
    uint64_t v66;
    uint64_t v68;
    uint64_t t17;
    uint64_t t34;
    v1 = p0;
    v2 = p1;
    v3 = p2;
    v4 = UINT64_C(0);
    v5 = (v2 == v4);
    if (v5) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v7 = UINT64_C(1);
    return v7;
b3:
    v9 = UINT64_C(5);
    v10 = (v2 > v9);
    if (v10) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v12 = UINT64_C(2);
    return v12;
b5:
    v14 = UINT64_C(0);
    v15 = UINT64_C(0);
    t34 = v14;
    t17 = v15;
    v34 = t34;
    v17 = t17;
    goto b6;
b6:
    v18 = (v17 < v2);
    if (v18) {
        goto b7;
    } else {
        goto b8;
    }
b7:
    v20 = UINT64_C(8);
    if (v17 >= v20) exsrt_abortus(1);
    v22 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v17 * 1);
    v23 = exsi_norm_u(exsi_ld_n(v22 + 0, 1), 8);
    v24 = UINT64_C(48);
    v25 = (v23 < v24);
    if (v25) {
        goto b10;
    } else {
        goto b11;
    }
b8:
    v45 = UINT64_C(0);
    v46 = UINT64_C(8);
    if (v45 >= v46) exsrt_abortus(1);
    v48 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v45 * 1);
    v49 = exsi_norm_u(exsi_ld_n(v48 + 0, 1), 8);
    v50 = UINT64_C(48);
    v51 = (v49 == v50);
    if (v51) {
        goto b14;
    } else {
        goto b15;
    }
b9:
    v42 = UINT64_C(1);
    v43 = v17 + v42;
    t34 = v40;
    t17 = v43;
    v34 = t34;
    v17 = t17;
    goto b6;
b10:
    v27 = UINT64_C(3);
    return v27;
b11:
    v29 = UINT64_C(57);
    v30 = (v23 > v29);
    if (v30) {
        goto b12;
    } else {
        goto b13;
    }
b12:
    v32 = UINT64_C(3);
    return v32;
b13:
    v35 = UINT64_C(10);
    v36 = exsi_mul_u(v34, v35, 32);
    v37 = exsi_norm_u(exsi_norm_u(v23, 8), 32);
    v38 = UINT64_C(48);
    v39 = exsi_sub_u(v37, v38, 32);
    v40 = exsi_add_u(v36, v39, 32);
    goto b9;
b14:
    v53 = UINT64_C(1);
    v54 = (v2 > v53);
    if (v54) {
        goto b16;
    } else {
        goto b17;
    }
b15:
    v59 = UINT64_C(0);
    v60 = (v34 == v59);
    if (v60) {
        goto b18;
    } else {
        goto b19;
    }
b16:
    v56 = UINT64_C(4);
    return v56;
b17:
    goto b15;
b18:
    v62 = UINT64_C(5);
    return v62;
b19:
    v64 = (v34 > v3);
    if (v64) {
        goto b20;
    } else {
        goto b21;
    }
b20:
    v66 = UINT64_C(5);
    return v66;
b21:
    v68 = UINT64_C(0);
    return v68;
}

uint64_t exs_admitte_portum(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(65535);
    v4 = exs_numerus_iudica(v1, v2, v3);
    return v4;
}

uint64_t exs_admitte_intervallum(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(3600);
    v4 = exs_numerus_iudica(v1, v2, v3);
    return v4;
}

